version: '3.8'
services:
  nodejs:
    restart: unless-stopped
    build:
      context: ./
      target: production
    working_dir: /app
    ports:
      - '1883:1883'
    command: node build/index.js
