version: '3.8'
services:
  nodejs:
    restart: unless-stopped
    build:
      context: ./
      target: production
    working_dir: /app
    command: node build/index.js
    environment:
      SLACK_BOT_TOKEN: '${SLACK_BOT_TOKEN}'
      SLACK_SIGNING_SECRET: '${SLACK_SIGNING_SECRET}'
      SLACK_APP_TOKEN: '${SLACK_APP_TOKEN}'
